
package com.sample.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeRecUpdatorImplService", targetNamespace = "http://impl.service.sample.com/", wsdlLocation = "http://127.0.0.1:9999/updateEmpRecord?wsdl")
public class EmployeeRecUpdatorImplService
    extends Service
{

    private final static URL EMPLOYEERECUPDATORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEERECUPDATORIMPLSERVICE_EXCEPTION;
    private final static QName EMPLOYEERECUPDATORIMPLSERVICE_QNAME = new QName("http://impl.service.sample.com/", "EmployeeRecUpdatorImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/updateEmpRecord?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEERECUPDATORIMPLSERVICE_WSDL_LOCATION = url;
        EMPLOYEERECUPDATORIMPLSERVICE_EXCEPTION = e;
    }

    public EmployeeRecUpdatorImplService() {
        super(__getWsdlLocation(), EMPLOYEERECUPDATORIMPLSERVICE_QNAME);
    }

    public EmployeeRecUpdatorImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEERECUPDATORIMPLSERVICE_QNAME, features);
    }

    public EmployeeRecUpdatorImplService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEERECUPDATORIMPLSERVICE_QNAME);
    }

    public EmployeeRecUpdatorImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEERECUPDATORIMPLSERVICE_QNAME, features);
    }

    public EmployeeRecUpdatorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeRecUpdatorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEmployeeUpdator
     */
    @WebEndpoint(name = "EmployeeRecUpdatorImplPort")
    public IEmployeeUpdator getEmployeeRecUpdatorImplPort() {
        return super.getPort(new QName("http://impl.service.sample.com/", "EmployeeRecUpdatorImplPort"), IEmployeeUpdator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEmployeeUpdator
     */
    @WebEndpoint(name = "EmployeeRecUpdatorImplPort")
    public IEmployeeUpdator getEmployeeRecUpdatorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.sample.com/", "EmployeeRecUpdatorImplPort"), IEmployeeUpdator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEERECUPDATORIMPLSERVICE_EXCEPTION!= null) {
            throw EMPLOYEERECUPDATORIMPLSERVICE_EXCEPTION;
        }
        return EMPLOYEERECUPDATORIMPLSERVICE_WSDL_LOCATION;
    }

}
