
package com.sample.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.sample.service.api.EmpRecordUpdateReq;
import com.sample.service.api.EmpRecordUpdateRes;
import com.sample.service.api.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEmployeeUpdator", targetNamespace = "http://api.service.sample.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEmployeeUpdator {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sample.service.api.EmpRecordUpdateRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEmployeeRecord", targetNamespace = "http://api.service.sample.com/", className = "com.sample.service.api.UpdateEmployeeRecord")
    @ResponseWrapper(localName = "updateEmployeeRecordResponse", targetNamespace = "http://api.service.sample.com/", className = "com.sample.service.api.UpdateEmployeeRecordResponse")
    @Action(input = "http://api.service.sample.com/IEmployeeUpdator/updateEmployeeRecordRequest", output = "http://api.service.sample.com/IEmployeeUpdator/updateEmployeeRecordResponse")
    public EmpRecordUpdateRes updateEmployeeRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        EmpRecordUpdateReq arg0);

}
